export interface TemplateField {
  key: string;
  label: string;
  type: 'string' | 'number' | 'boolean' | 'select' | 'textarea';
  required?: boolean;
  options?: string[];
  placeholder?: string;
  hint?: string;
}

export interface UsageTemplate {
  id: string;
  label: string;
  description: string;
  fields: TemplateField[];
}

export interface TemplateRenderCtx {
  readBuiltinSource(name: string): string | null;
}

export type RenderResult =
  | { ok: true; content: string; name: string }
  | { ok: false; error: string };

const AUTH_FIELDS: TemplateField[] = [
  { key: 'authMode', label: '认证方式', type: 'select', required: true, options: ['none', 'authKey', 'cookie', 'header'], hint: 'authKey=opencode 登录凭据；cookie=用量 cookies；header=自定义头（值存 pluginConfig.headerValue）' },
  { key: 'authName', label: '认证名（auth provider 或 cookie 名）', type: 'string' },
  { key: 'headerName', label: '自定义 header 名', type: 'string', hint: '仅 authMode=header 时使用' },
];

function jsValue(v: unknown): string {
  return JSON.stringify(v ?? null);
}

function pickFn(): string {
  return [
    'function pick(obj, path) {',
    '  if (!path) return undefined;',
    '  return path.split(".").reduce((acc, k) => (acc == null ? undefined : acc[k]), obj);',
    '}',
  ].join('\n');
}

function authBlock(name: string): string[] {
  return [
    `  const pc = ctx.pluginConfig(${jsValue(name)}) || {};`,
    '  const cfg = { ...CFG, ...pc };',
    '  const headers = {};',
    "  if (cfg.authMode === 'authKey') {",
    '    const key = ctx.apiKey(cfg.authName);',
    '    if (!key) return null;',
    "    headers.Authorization = 'Bearer ' + key;",
    "  } else if (cfg.authMode === 'cookie') {",
    '    const cookie = ctx.cookie(cfg.authName);',
    '    if (!cookie) return null;',
    '    headers.Cookie = cookie;',
    "  } else if (cfg.authMode === 'header') {",
    "    headers[cfg.headerName || 'X-Api-Key'] = pc.headerValue || '';",
    '  }',
  ];
}

function renderBalanceApi(v: Record<string, any>): string {
  const name = v.name;
  const schema = [
    { key: 'endpoint', label: 'Endpoint URL', type: 'string', default: v.endpoint },
    { key: 'usedPath', label: 'used 字段路径', type: 'string', default: v.usedPath },
    { key: 'limitPath', label: 'limit 字段路径', type: 'string', default: v.limitPath },
    { key: 'remainingPath', label: 'remaining 字段路径', type: 'string', default: v.remainingPath },
  ];
  return [
    `// Generated by MAFW usage template 'balance-api'`,
    `// 参数可在 Config → Usage 插件详情表单修改（存 usage.pluginConfig），或直接编辑本文件`,
    `const CFG = ${jsValue({ name, displayName: v.displayName || name, authMode: v.authMode || 'none', authName: v.authName || '', headerName: v.headerName || '', endpoint: v.endpoint, usedPath: v.usedPath || '', limitPath: v.limitPath || '', remainingPath: v.remainingPath || '' })};`,
    `const SCHEMA = ${jsValue(schema)};`,
    pickFn(),
    `async function main(ctx) {`,
    ...authBlock(name),
    '  const res = await ctx.fetch(cfg.endpoint, { headers });',
    "  if (!res.ok) { ctx.log.warn('[' + CFG.name + '] HTTP ' + res.status); return null; }",
    '  const data = await res.json();',
    '  const used = pick(data, cfg.usedPath);',
    '  const limit = pick(data, cfg.limitPath);',
    '  const remaining = pick(data, cfg.remainingPath);',
    '  if (limit === undefined && remaining === undefined) return null;',
    '  const u = Number(used !== undefined ? used : (limit !== undefined && remaining !== undefined ? limit - remaining : 0));',
    '  const l = Number(limit !== undefined ? limit : u + Number(remaining || 0));',
    '  if (!isFinite(u) || !isFinite(l) || l <= 0) return null;',
    "  return { name: CFG.name, type: 'api', plan: CFG.displayName, windows: [{ window: 'balance', used: u, limit: l, unit: '$', pct: Math.min(100, Math.round((u / l) * 100)), remaining }] };",
    '}',
    `module.exports = { name: ${jsValue(name)}, type: 'api', plan: ${jsValue(v.displayName || name)}, configSchema: SCHEMA, fetch: (ctx) => main(ctx) };`,
  ].join('\n');
}

function renderTokenPlan(v: Record<string, any>): string {
  const name = v.name;
  const schema = [
    { key: 'endpoint', label: 'Endpoint URL', type: 'string', default: v.endpoint },
    { key: 'listPath', label: '窗口列表字段路径', type: 'string', default: v.listPath },
    { key: 'windowField', label: '窗口名字段', type: 'string', default: v.windowField || 'window' },
    { key: 'pctField', label: '百分比字段', type: 'string', default: v.pctField || 'pct' },
    { key: 'usedField', label: 'used 字段（可选）', type: 'string', default: v.usedField || '' },
    { key: 'limitField', label: 'limit 字段（可选）', type: 'string', default: v.limitField || '' },
    { key: 'resetAtField', label: 'resetAt 字段（可选）', type: 'string', default: v.resetAtField || '' },
  ];
  return [
    `// Generated by MAFW usage template 'token-plan'`,
    `// 参数可在 Config → Usage 插件详情表单修改（存 usage.pluginConfig），或直接编辑本文件`,
    `const CFG = ${jsValue({ name, displayName: v.displayName || name, authMode: v.authMode || 'none', authName: v.authName || '', headerName: v.headerName || '', endpoint: v.endpoint, listPath: v.listPath || '', windowField: v.windowField || 'window', pctField: v.pctField || 'pct', usedField: v.usedField || '', limitField: v.limitField || '', resetAtField: v.resetAtField || '' })};`,
    `const SCHEMA = ${jsValue(schema)};`,
    pickFn(),
    `async function main(ctx) {`,
    ...authBlock(name),
    '  const res = await ctx.fetch(cfg.endpoint, { headers });',
    "  if (!res.ok) { ctx.log.warn('[' + CFG.name + '] HTTP ' + res.status); return null; }",
    '  const data = await res.json();',
    '  const list = pick(data, cfg.listPath);',
    '  if (!Array.isArray(list)) return null;',
    '  const windows = list.map((it) => {',
    '    const w = {',
    '      window: String(it[cfg.windowField] || "balance"),',
    '      used: Number(cfg.usedField ? (it[cfg.usedField] || 0) : 0),',
    '      limit: Number(cfg.limitField ? (it[cfg.limitField] || 0) : 0),',
    '      unit: cfg.limitField ? "$" : "pct",',
    '      pct: Math.round(Number(it[cfg.pctField] || 0)),',
    '    };',
    '    const resetAt = cfg.resetAtField ? it[cfg.resetAtField] : undefined;',
    '    if (resetAt) w.resetAt = Number(resetAt);',
    '    return w;',
    '  });',
    '  if (windows.length === 0) return null;',
    `  return { name: CFG.name, type: 'token-plan', plan: CFG.displayName, windows };`,
    '}',
    `module.exports = { name: ${jsValue(name)}, type: 'token-plan', plan: ${jsValue(v.displayName || name)}, configSchema: SCHEMA, fetch: (ctx) => main(ctx) };`,
  ].join('\n');
}

function renderClone(v: Record<string, any>, ctx: TemplateRenderCtx): RenderResult {
  const src = ctx.readBuiltinSource(v.sourceName);
  if (!src) return { ok: false, error: `builtin plugin '${v.sourceName}' not found` };
  const header = `// Cloned from builtin '${v.sourceName}' by MAFW — edit freely (this file overrides the builtin).\n`;
  return { ok: true, content: header + src, name: String(v.sourceName) };
}

function renderBlank(v: Record<string, any>): string {
  const name = v.name;
  return [
    `// Created from MAFW usage template 'blank' — implement fetch(ctx) per the README in this directory.`,
    `module.exports = {`,
    `  name: ${jsValue(name)},`,
    `  type: 'api',`,
    `  plan: ${jsValue(name)},`,
    `  // configSchema: [{ key: 'endpoint', label: 'Endpoint', type: 'string' }],`,
    `  async fetch(ctx) {`,
    `    return null; // return { name, type, plan, windows: [...] } or null to hide`,
    `  },`,
    `};`,
  ].join('\n');
}

const TEMPLATES: (UsageTemplate & { render(values: Record<string, any>, ctx: TemplateRenderCtx): RenderResult })[] = [
  {
    id: 'balance-api',
    label: '余额型 API',
    description: '查询余额/额度（balance 窗口），填 endpoint + JSON 字段路径',
    fields: [
      { key: 'name', label: '插件名（providerID）', type: 'string', required: true, placeholder: 'my-gateway' },
      { key: 'displayName', label: '显示名', type: 'string' },
      ...AUTH_FIELDS,
      { key: 'endpoint', label: 'Endpoint URL', type: 'string', required: true, placeholder: 'https://api.example.com/v1/balance' },
      { key: 'usedPath', label: 'used 字段路径', type: 'string', placeholder: 'data.used' },
      { key: 'limitPath', label: 'limit 字段路径', type: 'string', placeholder: 'data.limit' },
      { key: 'remainingPath', label: 'remaining 字段路径', type: 'string', placeholder: 'data.remaining' },
    ],
    render: (v) => ({ ok: true, content: renderBalanceApi(v), name: String(v.name) }),
  },
  {
    id: 'token-plan',
    label: '套餐窗口型',
    description: '5h/7d/month 等窗口配额，endpoint 返回窗口列表 JSON',
    fields: [
      { key: 'name', label: '插件名（providerID）', type: 'string', required: true, placeholder: 'my-plan' },
      { key: 'displayName', label: '显示名', type: 'string' },
      ...AUTH_FIELDS,
      { key: 'endpoint', label: 'Endpoint URL', type: 'string', required: true },
      { key: 'listPath', label: '窗口列表字段路径', type: 'string', placeholder: 'data.items', hint: '指向 JSON 数组' },
      { key: 'windowField', label: '窗口名字段', type: 'string', placeholder: 'window' },
      { key: 'pctField', label: '百分比字段', type: 'string', placeholder: 'pct' },
      { key: 'usedField', label: 'used 字段（可选）', type: 'string' },
      { key: 'limitField', label: 'limit 字段（可选）', type: 'string' },
      { key: 'resetAtField', label: 'resetAt 字段（可选，epoch ms）', type: 'string' },
    ],
    render: (v) => ({ ok: true, content: renderTokenPlan(v), name: String(v.name) }),
  },
  {
    id: 'clone-builtin',
    label: '克隆内置插件',
    description: '拷贝一份内置适配器到用户目录（覆盖内置），可自由编辑',
    fields: [
      { key: 'sourceName', label: '选择内置插件', type: 'select', required: true },
    ],
    render: (v, ctx) => renderClone(v, ctx),
  },
  {
    id: 'blank',
    label: '空白自定义',
    description: '空骨架，实现 fetch(ctx) 接口即可',
    fields: [
      { key: 'name', label: '插件名（providerID）', type: 'string', required: true },
    ],
    render: (v) => ({ ok: true, content: renderBlank(v), name: String(v.name) }),
  },
];

export const USAGE_TEMPLATES: UsageTemplate[] = TEMPLATES.map(({ id, label, description, fields }) => ({ id, label, description, fields }));

export function renderTemplate(id: string, values: Record<string, any>, ctx: TemplateRenderCtx): RenderResult {
  const tpl = TEMPLATES.find(t => t.id === id);
  if (!tpl) return { ok: false, error: `unknown template '${id}'` };
  const name = values?.name;
  if (id !== 'clone-builtin' && (!name || !/^[a-z0-9][a-z0-9-]{0,63}$/.test(String(name)))) {
    return { ok: false, error: '插件名必填且只能含小写字母/数字/连字符' };
  }
  const missing = tpl.fields.filter(f => f.required && (values?.[f.key] === undefined || values?.[f.key] === ''));
  if (id !== 'clone-builtin' && missing.length > 0) {
    return { ok: false, error: `缺少必填字段: ${missing.map(f => f.label).join(', ')}` };
  }
  return tpl.render(values ?? {}, ctx);
}
