// One-time data-directory migration: the memory store (T1 db, harmonic index,
// reflect cursor) and pipeline runtime files moved from the project-relative
// .mafw (which depended on the gateway's working directory / MAFW_PROJECT_DIR)
// to the gateway package's own .mafw (fixed path). Idempotent via a
// .data-migrated marker (the target memory dir may already exist as an empty
// store created by class-field initialization). The legacy directory is
// DELETED after a successful move (user-confirmed policy).
import * as fs from 'fs';
import * as path from 'path';
import { log } from '../core/utils/logger';

export interface DataDirMigrateResult {
  migrated: boolean;
  moved: string[];
  legacyRemoved: boolean;
}

const MARKER = '.data-migrated';
const LEGACY = '.mafw-before-gateway-move';

export function migrateDataDir(targetMafwDir: string, legacyProjectMafwDir: string): DataDirMigrateResult {
  const result: DataDirMigrateResult = { migrated: false, moved: [], legacyRemoved: false };
  const marker = path.join(targetMafwDir, MARKER);

  // Already migrated (or nothing to do): fixed location is authoritative.
  if (fs.existsSync(marker) || !fs.existsSync(legacyProjectMafwDir)) {
    return result;
  }

  try {
    fs.mkdirSync(targetMafwDir, { recursive: true });

    // Move the durable, hard-to-recreate pieces; everything else (events,
    // registry, logs…) is regenerated by the gateway itself. A pre-existing
    // target entry can only be an empty store created by field init — drop it
    // before the rename so real legacy data wins.
    const movable = [
      'memory',
      'recall-reflect-cursor.json',
      'manager-session.json',
      'automations',
      'config.yaml',
      'constraints.json',
      'constraints.migrated.json',
      'parametric',
      'state',
      'goals',
      'requests',
      'lessons',
      'reviews',
      'handoffs',
      'decisions',
      'checkpoints',
      'tasks',
    ];
    for (const name of movable) {
      const src = path.join(legacyProjectMafwDir, name);
      if (!fs.existsSync(src)) continue;
      const dest = path.join(targetMafwDir, name);
      if (fs.existsSync(dest)) {
        fs.rmSync(dest, { recursive: true, force: true });
      }
      fs.renameSync(src, dest);
      result.moved.push(name);
    }

    // Delete the legacy directory (user-confirmed policy: no backup kept).
    if (fs.existsSync(legacyProjectMafwDir)) {
      const entries = fs.readdirSync(legacyProjectMafwDir);
      if (entries.length === 0) {
        fs.rmdirSync(legacyProjectMafwDir);
        result.legacyRemoved = true;
      } else {
        // regenerable leftovers: rename aside and delete immediately
        const renamed = path.join(path.dirname(legacyProjectMafwDir), LEGACY);
        if (!fs.existsSync(renamed)) {
          fs.renameSync(legacyProjectMafwDir, renamed);
          fs.rmSync(renamed, { recursive: true, force: true });
          result.legacyRemoved = true;
        }
      }
    }

    fs.writeFileSync(marker, new Date().toISOString(), 'utf-8');
    result.migrated = result.moved.length > 0;
    if (result.migrated) {
      log.info(
        `[data-dir] migrated memory data to ${targetMafwDir}: ${result.moved.join(', ')} (legacy removed: ${result.legacyRemoved})`,
      );
    }
  } catch (err: any) {
    log.warn(`[data-dir] migration failed (non-fatal): ${err.message}`);
    result.migrated = false;
  }

  return result;
}
