/**
 * P4-A：从 RouteRegistry catalog 生成 OpenAPI paths 片段。
 *
 * 运行：cd gateway && npx ts-node --project tsconfig.json scripts/emit-openapi.ts
 * 产物：packages/gateway-sdk/contract/gateway-paths.json（check-in，可 review）
 *
 * 这是 spec 的"事实源"出口：catalog（gateway 源码的一部分）→ gateway-paths.json
 * → SDK merge-contract.mjs 合并 overrides.json → openapi.json → openapi-typescript。
 * catalog 变更后必须重跑本脚本——api-contract.test.ts 的新鲜度测试会把陈旧产物打红。
 */
import * as fs from 'fs';
import * as path from 'path';
import { RouteRegistry } from '../src/routes/registry';
import { buildRouteCatalog } from '../src/routes/route-catalog';

function main(): void {
  const registry = new RouteRegistry().register(...buildRouteCatalog());
  const paths = registry.toOpenApiPaths();
  const out = {
    $comment: 'Auto-generated by gateway/scripts/emit-openapi.ts from routes/route-catalog.ts — do not edit by hand; rerun the script after catalog changes.',
    paths,
  };
  const dest = path.join(__dirname, '..', '..', 'packages', 'gateway-sdk', 'contract', 'gateway-paths.json');
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, JSON.stringify(out, null, 2) + '\n', 'utf-8');
  const opCount = Object.values(paths).reduce((n, m) => n + Object.keys(m as object).length, 0);
  console.log(`[emit-openapi] ${registry.list().length} routes → ${Object.keys(paths).length} paths / ${opCount} operations → ${path.relative(process.cwd(), dest)}`);
}

main();
