import * as fs from 'fs';
import * as path from 'path';
import type { AgentDefinition } from '../agent-definition';

/**
 * pi agent configuration module
 * 
 * Translates gateway AgentDefinition into pi's format:
 * - System prompt → ~/.pi/agent/prompts/<name>.md
 * - Permissions → extension that intercepts tool_call events
 */

export interface PiAgentConfig {
  agentDir?: string; // defaults to ~/.pi/agent/
}

/**
 * Get the pi agent directory
 */
function getAgentDir(config?: PiAgentConfig): string {
  if (config?.agentDir) return config.agentDir;
  
  // Try to import pi's getAgentDir, fallback to default
  try {
    const piConfig = require('@earendil-works/pi-coding-agent/dist/config');
    return piConfig.getAgentDir();
  } catch {
    return path.join(process.env.HOME || process.env.USERPROFILE || '~', '.pi', 'agent');
  }
}

/**
 * Get the prompts directory
 */
function getPromptsDir(config?: PiAgentConfig): string {
  return path.join(getAgentDir(config), 'prompts');
}

/**
 * Get the extensions directory
 */
function getExtensionsDir(config?: PiAgentConfig): string {
  return path.join(getAgentDir(config), 'extensions');
}

/**
 * Install an agent definition into pi
 */
export async function install(name: string, definition: AgentDefinition, config?: PiAgentConfig): Promise<void> {
  const promptsDir = getPromptsDir(config);
  const extensionsDir = getExtensionsDir(config);
  
  // Ensure directories exist
  fs.mkdirSync(promptsDir, { recursive: true });
  fs.mkdirSync(extensionsDir, { recursive: true });
  
  // Write system prompt
  const promptPath = path.join(promptsDir, `${name}.md`);
  fs.writeFileSync(promptPath, definition.systemPrompt, 'utf-8');
  
  // Write permissions extension
  const extensionPath = path.join(extensionsDir, `${name}-permissions.js`);
  const extensionCode = generatePermissionsExtension(name, definition.permissions);
  fs.writeFileSync(extensionPath, extensionCode, 'utf-8');
}

/**
 * Remove an agent definition from pi
 */
export async function remove(name: string, config?: PiAgentConfig): Promise<void> {
  const promptsDir = getPromptsDir(config);
  const extensionsDir = getExtensionsDir(config);
  
  const promptPath = path.join(promptsDir, `${name}.md`);
  const extensionPath = path.join(extensionsDir, `${name}-permissions.js`);
  
  if (fs.existsSync(promptPath)) {
    fs.unlinkSync(promptPath);
  }
  
  if (fs.existsSync(extensionPath)) {
    fs.unlinkSync(extensionPath);
  }
}

/**
 * Generate a pi extension that enforces permissions
 */
function generatePermissionsExtension(name: string, permissions: AgentDefinition['permissions']): string {
  const editRule = permissions.edit || 'allow';
  const bashRule = permissions.bash || 'allow';
  
  // Build tool rules map
  const toolRules: Record<string, string> = {};
  if (permissions.tools) {
    Object.assign(toolRules, permissions.tools);
  }
  if (permissions.task) {
    // task permissions are for subagents, not tools
    // We'll handle them separately if needed
  }
  
  return `// Auto-generated permissions extension for agent: ${name}
// Generated by MAFW gateway

export default {
  name: '${name}-permissions',
  
  onToolCall(event, ctx) {
    const toolName = event.toolName;
    const toolRules = ${JSON.stringify(toolRules, null, 2)};
    
    // Check specific tool rules first
    if (toolRules[toolName]) {
      const rule = toolRules[toolName];
      if (rule === 'deny') {
        return { block: true, reason: 'denied by agent permissions' };
      }
      if (rule === 'ask') {
        // For 'ask', we'd need to prompt the user
        // For now, treat as deny
        return { block: true, reason: 'requires approval (not implemented)' };
      }
      // 'allow' - continue
    }
    
    // Check category rules
    if (toolName === 'edit' || toolName === 'write') {
      const rule = '${editRule}';
      if (rule === 'deny') {
        return { block: true, reason: 'edit/write denied by agent permissions' };
      }
      if (rule === 'ask') {
        return { block: true, reason: 'edit/write requires approval (not implemented)' };
      }
    }
    
    if (toolName === 'bash') {
      const rule = '${bashRule}';
      if (rule === 'deny') {
        return { block: true, reason: 'bash denied by agent permissions' };
      }
      if (rule === 'ask') {
        return { block: true, reason: 'bash requires approval (not implemented)' };
      }
    }
    
    // Default: allow
    return { block: false };
  }
};
`;
}

/**
 * List installed agents
 */
export async function list(config?: PiAgentConfig): Promise<string[]> {
  const promptsDir = getPromptsDir(config);
  
  if (!fs.existsSync(promptsDir)) {
    return [];
  }
  
  const files = fs.readdirSync(promptsDir);
  return files
    .filter(f => f.endsWith('.md'))
    .map(f => f.replace(/\.md$/, ''));
}

/**
 * Get an agent definition
 */
export async function get(name: string, config?: PiAgentConfig): Promise<AgentDefinition | null> {
  const promptsDir = getPromptsDir(config);
  const promptPath = path.join(promptsDir, `${name}.md`);
  
  if (!fs.existsSync(promptPath)) {
    return null;
  }
  
  const systemPrompt = fs.readFileSync(promptPath, 'utf-8');
  
  // Try to load permissions from extension
  const extensionsDir = getExtensionsDir(config);
  const extensionPath = path.join(extensionsDir, `${name}-permissions.js`);
  
  let permissions: AgentDefinition['permissions'] = {
    edit: 'allow',
    bash: 'allow',
    tools: {},
    task: {}
  };
  
  if (fs.existsSync(extensionPath)) {
    // Parse the extension to extract permissions
    // This is a simplified parser - in production, we'd want to be more robust
    const extensionCode = fs.readFileSync(extensionPath, 'utf-8');
    
    // Extract edit rule
    const editMatch = extensionCode.match(/const rule = '([^']+)';\s+if \(rule === 'deny'\) \{\s+return \{ block: true, reason: 'edit\/write denied/);
    if (editMatch) {
      permissions.edit = editMatch[1] as any;
    }
    
    // Extract bash rule
    const bashMatch = extensionCode.match(/const rule = '([^']+)';\s+if \(rule === 'deny'\) \{\s+return \{ block: true, reason: 'bash denied/);
    if (bashMatch) {
      permissions.bash = bashMatch[1] as any;
    }
    
    // Extract tool rules
    const toolRulesMatch = extensionCode.match(/const toolRules = ({[^}]+});/);
    if (toolRulesMatch) {
      try {
        permissions.tools = JSON.parse(toolRulesMatch[1]);
      } catch {
        // Ignore parse errors
      }
    }
  }
  
  return {
    description: `Agent: ${name}`,
    mode: 'all',
    systemPrompt,
    permissions
  };
}
