import * as fs from 'fs';
import * as path from 'path';
import type { AgentDefinition, AgentPermissions } from '../agent-definition';

/**
 * pi agent configuration module
 *
 * Translates gateway AgentDefinition into pi's format:
 * - System prompt → ~/.pi/agent/prompts/<name>.md
 * - Permissions → extension that intercepts tool_call events (pi ExtensionAPI format)
 * - Metadata → ~/.pi/agent/metadata/<name>.json (for reliable round-trip)
 *
 * Extensions are loaded at session creation time via `loadAgentExtensions()` and
 * passed to `createAgentSession()` via `resourceLoader.extensionFactories`.
 */

export interface PiAgentConfig {
  agentDir?: string; // defaults to ~/.pi/agent/
}

/** Stored metadata for round-trip fidelity */
interface AgentMetadata {
  description: string;
  mode?: string;
  model?: string;
  temperature?: number;
  color?: string;
  permissions: AgentPermissions;
}

/**
 * Get the pi agent directory
 */
export function getAgentDir(config?: PiAgentConfig): string {
  if (config?.agentDir) return config.agentDir;

  // Try to import pi's getAgentDir, fallback to default
  try {
    const piConfig = require('@earendil-works/pi-coding-agent/dist/config');
    return piConfig.getAgentDir();
  } catch {
    return path.join(process.env.HOME || process.env.USERPROFILE || '~', '.pi', 'agent');
  }
}

/**
 * Get the prompts directory
 */
export function getPromptsDir(config?: PiAgentConfig): string {
  return path.join(getAgentDir(config), 'prompts');
}

/**
 * Get the extensions directory
 */
export function getExtensionsDir(config?: PiAgentConfig): string {
  return path.join(getAgentDir(config), 'extensions');
}

/**
 * Get the metadata directory
 */
function getMetadataDir(config?: PiAgentConfig): string {
  return path.join(getAgentDir(config), 'metadata');
}

/**
 * Install an agent definition into pi
 */
export async function install(name: string, definition: AgentDefinition, config?: PiAgentConfig): Promise<void> {
  const promptsDir = getPromptsDir(config);
  const extensionsDir = getExtensionsDir(config);
  const metadataDir = getMetadataDir(config);

  // Ensure directories exist
  fs.mkdirSync(promptsDir, { recursive: true });
  fs.mkdirSync(extensionsDir, { recursive: true });
  fs.mkdirSync(metadataDir, { recursive: true });

  // Write system prompt
  const promptPath = path.join(promptsDir, `${name}.md`);
  fs.writeFileSync(promptPath, definition.systemPrompt, 'utf-8');

  // Write permissions extension (pi ExtensionAPI format)
  const extensionPath = path.join(extensionsDir, `${name}-permissions.js`);
  const extensionCode = generatePermissionsExtension(name, definition.permissions);
  fs.writeFileSync(extensionPath, extensionCode, 'utf-8');

  // Write metadata for reliable round-trip
  const metadataPath = path.join(metadataDir, `${name}.json`);
  const metadata: AgentMetadata = {
    description: definition.description,
    mode: definition.mode,
    model: definition.model,
    temperature: definition.temperature,
    color: definition.color,
    permissions: definition.permissions,
  };
  fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 2), 'utf-8');
}

/**
 * Remove an agent definition from pi
 */
export async function remove(name: string, config?: PiAgentConfig): Promise<void> {
  const promptsDir = getPromptsDir(config);
  const extensionsDir = getExtensionsDir(config);
  const metadataDir = getMetadataDir(config);

  const promptPath = path.join(promptsDir, `${name}.md`);
  const extensionPath = path.join(extensionsDir, `${name}-permissions.js`);
  const metadataPath = path.join(metadataDir, `${name}.json`);

  if (fs.existsSync(promptPath)) {
    fs.unlinkSync(promptPath);
  }

  if (fs.existsSync(extensionPath)) {
    fs.unlinkSync(extensionPath);
  }

  if (fs.existsSync(metadataPath)) {
    fs.unlinkSync(metadataPath);
  }
}

/**
 * Sanitize a name for use as a JavaScript function name
 */
function sanitizeFunctionName(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, '_');
}

/**
 * Generate a pi extension that enforces permissions.
 *
 * Format: `export default function(pi) { pi.on('tool_call', handler) }`
 * This matches pi's ExtensionFactory type: (pi: ExtensionAPI) => void | Promise<void>
 */
function generatePermissionsExtension(name: string, permissions: AgentPermissions): string {
  const editRule = permissions.edit || 'allow';
  const bashRule = permissions.bash || 'allow';

  // Build tool rules map (specific tool overrides)
  const toolRules: Record<string, string> = {};
  if (permissions.tools) {
    Object.assign(toolRules, permissions.tools);
  }

  const funcName = sanitizeFunctionName(name);
  const toolRulesJson = JSON.stringify(toolRules, null, 2);
  const editRuleJson = JSON.stringify(editRule);
  const bashRuleJson = JSON.stringify(bashRule);

  const lines: string[] = [
    `// Auto-generated permissions extension for agent: ${name}`,
    `// Generated by MAFW gateway — pi ExtensionAPI format`,
    `// ExtensionFactory: (pi: ExtensionAPI) => void`,
    ``,
    `export default function ${funcName}_permissions(pi) {`,
    `  const toolRules = ${toolRulesJson};`,
    ``,
    `  pi.on('tool_call', async (event, ctx) => {`,
    `    const toolName = event.toolName;`,
    ``,
    `    // Check specific tool rules first`,
    `    if (toolRules[toolName]) {`,
    `      const rule = toolRules[toolName];`,
    `      if (rule === 'deny') {`,
    `        return { block: true, reason: 'denied by agent permissions' };`,
    `      }`,
    `      if (rule === 'ask') {`,
    `        return { block: true, reason: 'requires approval (not implemented)' };`,
    `      }`,
    `      // 'allow' — fall through to category checks`,
    `    }`,
    ``,
    `    // Check category rules`,
    `    if (toolName === 'edit' || toolName === 'write') {`,
    `      const rule = ${editRuleJson};`,
    `      if (rule === 'deny') {`,
    `        return { block: true, reason: 'edit/write denied by agent permissions' };`,
    `      }`,
    `      if (rule === 'ask') {`,
    `        return { block: true, reason: 'edit/write requires approval (not implemented)' };`,
    `      }`,
    `    }`,
    ``,
    `    if (toolName === 'bash') {`,
    `      const rule = ${bashRuleJson};`,
    `      if (rule === 'deny') {`,
    `        return { block: true, reason: 'bash denied by agent permissions' };`,
    `      }`,
    `      if (rule === 'ask') {`,
    `        return { block: true, reason: 'bash requires approval (not implemented)' };`,
    `      }`,
    `    }`,
    ``,
    `    // Default: allow`,
    `    return { block: false };`,
    `  });`,
    `}`,
    ``,
  ];

  return lines.join('\n');
}

/**
 * Load agent-specific permission extensions from disk.
 * Returns pi InlineExtension objects suitable for `resourceLoader.extensionFactories`.
 *
 * @param agentName - Agent name (e.g., 'manager')
 * @param config - Optional pi agent config
 * @returns Array of InlineExtension objects for createAgentSession
 */
export async function loadAgentExtensions(
  agentName: string,
  config?: PiAgentConfig,
): Promise<Array<{ name: string; factory: (pi: any) => void }>> {
  const extensionsDir = getExtensionsDir(config);
  const extensionPath = path.join(extensionsDir, `${agentName}-permissions.js`);

  if (!fs.existsSync(extensionPath)) {
    return [];
  }

  try {
    // Dynamic import for ESM extension file
    // Use file:// URL for Windows compatibility
    const fileUrl = `file:///${extensionPath.replace(/\\/g, '/')}`;
    const mod = await import(fileUrl);
    const factory = mod.default;

    if (typeof factory !== 'function') {
      console.warn(`[PiAgentConfig] Extension ${agentName} does not export a default function`);
      return [];
    }

    return [{
      name: `${agentName}-permissions`,
      factory,
    }];
  } catch (err: any) {
    console.warn(`[PiAgentConfig] Failed to load extension ${agentName}: ${err.message}`);
    return [];
  }
}

/**
 * List installed agents
 */
export async function list(config?: PiAgentConfig): Promise<string[]> {
  const promptsDir = getPromptsDir(config);

  if (!fs.existsSync(promptsDir)) {
    return [];
  }

  const files = fs.readdirSync(promptsDir);
  return files
    .filter(f => f.endsWith('.md'))
    .map(f => f.replace(/\.md$/, ''));
}

/**
 * Get an agent definition (reads from metadata + prompt files for reliable round-trip)
 */
export async function get(name: string, config?: PiAgentConfig): Promise<AgentDefinition | null> {
  const promptsDir = getPromptsDir(config);
  const promptPath = path.join(promptsDir, `${name}.md`);

  if (!fs.existsSync(promptPath)) {
    return null;
  }

  const systemPrompt = fs.readFileSync(promptPath, 'utf-8');

  // Read metadata for round-trip fidelity
  const metadataDir = getMetadataDir(config);
  const metadataPath = path.join(metadataDir, `${name}.json`);

  if (fs.existsSync(metadataPath)) {
    try {
      const metadata: AgentMetadata = JSON.parse(fs.readFileSync(metadataPath, 'utf-8'));
      return {
        description: metadata.description,
        mode: (metadata.mode as any) || 'all',
        model: metadata.model,
        temperature: metadata.temperature,
        color: metadata.color,
        systemPrompt,
        permissions: metadata.permissions,
      };
    } catch (err: any) {
      console.warn(`[PiAgentConfig] Failed to parse metadata for ${name}: ${err.message}`);
    }
  }

  // Fallback: return basic definition without metadata
  return {
    description: `Agent: ${name}`,
    mode: 'all',
    systemPrompt,
    permissions: {
      edit: 'allow',
      bash: 'allow',
      tools: {},
      task: {},
    },
  };
}
