import * as fs from 'fs';
import * as path from 'path';

/**
 * Report Generator — 执行报告生成器
 *
 * 职责：
 *   1. Goal 成功完成时生成成功报告
 *   2. 降级完成时生成降级报告
 *   3. Archive 阶段调用 L3 Validator
 *
 * 输出：.mafw/reports/{goal_id}.md
 */
export class ReportGenerator {
  private reportsDir: string;

  constructor(projectDir: string = '.') {
    this.reportsDir = path.join(projectDir, '.mafw/reports');
    if (!fs.existsSync(this.reportsDir)) fs.mkdirSync(this.reportsDir, { recursive: true });
  }

  /**
   * 生成成功报告
   */
  async generate(goalId: string, data: {
    loopCount: number;
    executeResult: any;
    reviewResult: any;
  }): Promise<string> {
    const reportPath = path.join(this.reportsDir, `${goalId}.md`);
    const lines = [
      `# MAFW 执行报告 — ${goalId}`,
      '',
      `> Goal ID: ${goalId}`,
      `> 完成时间: ${new Date().toISOString()}`,
      `> Loop 迭代: ${data.loopCount} 次`,
      '',
      '## 1. 执行摘要',
      '',
      '实现目标已完成。',
      '',
      '- **初始目标**: ' + goalId,
      '- **最终状态**: ✅ 全部指标达成',
      `- **Loop 迭代**: ${data.loopCount} 次`,
      '',
      '## 2. Wave 执行摘要',
      '',
      '| Wave | 名称 | Task 数 | 状态 |',
      '|------|------|---------|------|',
      ...(data.executeResult.waves || []).map((w: any, i: number) =>
        `| ${i + 1} | ${w.waveId} | ${w.tasks?.length || 0} | ✅ |`
      ),
      '',
      '## 3. 指标达成情况',
      '',
      '| 指标 | 目标 | 实际 | 状态 |',
      '|------|------|------|------|',
      '| Review verdict | pass | pass | ✅ |',
      '',
      '## 4. L3 Parametric Memory 固化清单',
      '',
      '> 详见 parametric/base-skill-manifest.yaml',
      '',
      '---',
      '*Report generated by MAFW Loop Agent v2.0*',
      ''
    ];

    fs.writeFileSync(reportPath, lines.join('\n'), 'utf-8');
    return reportPath;
  }

  /**
   * 生成降级报告
   */
  async generateDegraded(goalId: string, data: {
    loopCount: number;
    reason: string;
    metrics: any;
  }): Promise<string> {
    const reportPath = path.join(this.reportsDir, `${goalId}-degraded.md`);
    const lines = [
      `# MAFW 降级报告 — ${goalId}`,
      '',
      `> Goal ID: ${goalId}`,
      `> 状态: 部分完成（降级）`,
      `> 原因: ${data.reason}`,
      '',
      '## 执行摘要',
      '',
      `- **计划目标**: ${goalId}`,
      `- **实际状态**: ${data.reason}`,
      `- **降级策略**: 自动降级`,
      `- **总 Loop**: ${data.loopCount}`,
      '',
      '## 建议后续操作',
      '',
      '1. 查看降级报告了解具体问题',
      '2. 修复后运行 `/skill mafw-loop` 继续迭代',
      '',
      '---',
      '*Degraded report generated by MAFW Loop Agent v2.0*',
      ''
    ];

    fs.writeFileSync(reportPath, lines.join('\n'), 'utf-8');
    return reportPath;
  }
}
